name: lol_custom_game_manager
description: League of Legends custom game manager app to handle mercenary recruitment and participation.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^16.3.2
  
  # State Management
  provider: ^6.1.5
  
  # Routing
  go_router: ^15.1.2
  
  # UI
  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.7
  cached_network_image: ^3.2.3
  shimmer: ^3.0.0
  flutter_rating_bar: ^4.0.1
  intl: ^0.20.2
  image_picker: ^1.1.2
  
  # Utils
  shared_preferences: ^2.2.0
  url_launcher: ^6.1.12
  logger: ^1.4.0
  http: ^1.1.0
  equatable: ^2.0.5
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - .env

  # Fonts configuration - commented out until font files are available
  # fonts:
  #   - family: Pretendard
  #     fonts:
  #       - asset: assets/fonts/Pretendard-Thin.otf
  #         weight: 100
  #       - asset: assets/fonts/Pretendard-ExtraLight.otf
  #         weight: 200
  #       - asset: assets/fonts/Pretendard-Light.otf
  #         weight: 300
  #       - asset: assets/fonts/Pretendard-Regular.otf
  #         weight: 400
  #       - asset: assets/fonts/Pretendard-Medium.otf
  #         weight: 500
  #       - asset: assets/fonts/Pretendard-SemiBold.otf
  #         weight: 600
  #       - asset: assets/fonts/Pretendard-Bold.otf
  #         weight: 700
  #       - asset: assets/fonts/Pretendard-ExtraBold.otf
  #         weight: 800
  #       - asset: assets/fonts/Pretendard-Black.otf
  #         weight: 900 