name: lol_custom_game_manager
description: "A League of Legends custom-game (내전) manager app."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  firebase_messaging: ^14.7.9
  cloud_functions: ^4.5.8
  
  # State management
  provider: ^6.1.1
  flutter_riverpod: ^2.4.9
  
  # Routing
  go_router: ^12.1.3
  
  # UI
  cupertino_icons: ^1.0.6
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  shimmer: ^3.0.0
  intl: ^0.18.1
  
  # Utils
  url_launcher: ^6.2.2
  shared_preferences: ^2.2.2
  image_picker: ^1.0.5
  geolocator: ^10.1.0
  timeago: ^3.6.0
  
  # Payment
  flutter_stripe: ^9.5.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/ 