---
name: lol_custom_game_manager
description: League of Legends custom game manager app to handle mercenary recruitment
  and participation.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  firebase_storage: ^12.4.6
  firebase_messaging: ^15.2.6
  cupertino_icons: "^1.0.8"
  flutter_svg: "^2.0.10+1"
  cached_network_image: ^3.4.1
  shimmer: "^3.0.0"
  flutter_rating_bar: "^4.0.1"
  image_picker: "^1.1.2"
  provider: "^6.1.2"
  go_router: ^15.1.2
  shared_preferences: "^2.3.2"
  url_launcher: ^6.3.1
  logger: "^2.4.0"
  http: "^1.2.2"
  equatable: "^2.0.5"
  uuid: "^4.5.1"
  intl: ^0.20.2
  flutter_local_notifications: ^19.2.1
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  webview_flutter: ^4.13.0
  cloud_functions: ^5.5.2
  flutter_dotenv: ^5.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.15
flutter:
  uses-material-design: true
  assets:
  - assets/images/
  - assets/images/app_logo.png
  - assets/images/tiers/
  - assets/images/lanes/
dependency_overrides:
