name: lol_custom_game_manager
description: League of Legends custom game manager app to handle mercenary recruitment and participation.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0
  firebase_messaging: ^14.7.10
  cloud_functions: ^4.6.0
  firebase_analytics: ^10.8.0
  
  # State Management
  provider: ^6.1.1
  
  # Routing
  go_router: ^13.0.1
  
  # UI
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  flutter_rating_bar: ^4.0.1
  image_picker: ^1.0.7
  intl: ^0.20.2
  url_launcher: ^6.2.4
  
  # Utilities
  equatable: ^2.0.5
  uuid: ^4.3.1
  shared_preferences: ^2.2.2
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.3
  flutter_dotenv: ^5.1.0
  logger: ^2.0.2+1
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  mockito: ^5.4.4
  fake_cloud_firestore: ^2.4.8

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    # - assets/fonts/  # Commented out until font files are added
    - .env

  # Commenting out fonts section until the actual font files are available
  # fonts:
  #   - family: Pretendard
  #     fonts:
  #       - asset: assets/fonts/Pretendard-Thin.otf
  #         weight: 100
  #       - asset: assets/fonts/Pretendard-ExtraLight.otf
  #         weight: 200
  #       - asset: assets/fonts/Pretendard-Light.otf
  #         weight: 300
  #       - asset: assets/fonts/Pretendard-Regular.otf
  #         weight: 400
  #       - asset: assets/fonts/Pretendard-Medium.otf
  #         weight: 500
  #       - asset: assets/fonts/Pretendard-SemiBold.otf
  #         weight: 600
  #       - asset: assets/fonts/Pretendard-Bold.otf
  #         weight: 700
  #       - asset: assets/fonts/Pretendard-ExtraBold.otf
  #         weight: 800
  #       - asset: assets/fonts/Pretendard-Black.otf
  #         weight: 900 